# 수출물가지수_품목별

In [2]:
# Data 불러오기
Export_Items_Original <- read.csv("../Data/Export_items.csv")

In [3]:
# head, tail 확인
head(Export_Items_Original)
tail(Export_Items_Original)

  통계표  X7.5.3.수출물가지수.품목별..2015.100.
1 항목명1       과일
2 항목명2 달러기준
3 단위    2015=100
4 가중치  0.9
5 변환    원자료
6 1971/01
  X7.5.3.수출물가지수.품목별..2015.100..1
1       신선수산물
2 달러기준
3 2015=100
4 0.7
5 원자료
6 8.06
  X7.5.3.수출물가지수.품목별..2015.100..2
1       냉동수산물
2 달러기준
3 2015=100
4 2
5 원자료
6 18.70
  X7.5.3.수출물가지수.품목별..2015.100..3
1       어육
2 달러기준
3 2015=100
4 0.2
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..4
1       김
2 달러기준
3 2015=100
4 2.5
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..5
1       라면
2 달러기준
3 2015=100
4 2.8
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..6
1       나프타
2 달러기준
3 2015=100
4 4.5
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..7
1       휘발유
2 달러기준
3 2015=100
4 10.3
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..8
1       제트유
2 달러기준
3 2015=100
4 14.9
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..9
1       등유
2 달러기준
3 2015=100
4 0.8
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..10
1       경유
2 달러기준
3 2015=100
4 23.9
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..11
1       벙커C유
2 달러기준
3 2015=100
4 5.7
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..12
1       정제혼합용원료유
2 달러기준
3 2015=100
4 7.7
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..13
1       윤활유
2 달러기준
3 2015=100
4 1.9
5 원자료
6
  X7.5.3.수출물가지수.품목별..2015.100..14
1       아스팔트
2 달러기준
3 2015=100
4 3.1
5 원자료
6

    통계표
614 2021/09
615 2021/10
616    7.5.3 수출물가지수(품목별)(2015=100)
617 통계담당 : 한국은행 경제통계국 물가통계팀(02-759-4437)
618 주 : 주1) : 금월지수는 잠정치이며
619 주2) : 2010년 이후 가중치는 매년 변경되며
    X7.5.3.수출물가지수.품목별..2015.100.
614 99.43
615 91.01
616
617
618  익월지수 공표시 확정됨
619  2021년 적용되는 가중치를 표기하였음.
    X7.5.3.수출물가지수.품목별..2015.100..1
614 127.73
615 127.67
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..2
614 131.92
615 132.33
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..3
614 112.27
615 109.88
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..4
614 129.60
615 128.45
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..5
614 101.72
615 101.18
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..6
614 141.71
615 158.73
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..7
614 123.88
615 144.52
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..8
614 127.49
615 137.60
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..9
614 123.33
615 143.67
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..10
614 124.62
615 144.92
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..11
614 160.96
615 171.31
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..12
614 275.65
615 281.96
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..13
614 111.80
615 112.09
616
617
618
619
    X7.5.3.수출물가지수.품목별..2015.100..14
614 149.57
615 157.99
616
617
618
619

In [4]:
# check the structure
str(Export_Items_Original)

'data.frame':	619 obs. of  16 variables:
 $ 통계표                                  : Factor w/ 619 levels "   7.5.3 수출물가지수(품목별)(2015=100)",..: 618 619 613 612 614 2 3 4 5 6 ...
 $ X7.5.3.수출물가지수.품목별..2015.100.   : Factor w/ 150 levels "","      과일",..: 2 149 48 5 150 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..1 : Factor w/ 461 levels "","      신선수산물",..: 2 460 342 3 461 439 436 440 445 441 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..2 : Factor w/ 497 levels "","      냉동수산물",..: 2 496 154 147 497 144 144 144 144 144 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..3 : Factor w/ 319 levels "","      어육",..: 2 318 272 3 319 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..4 : Factor w/ 187 levels "","      김",..: 2 186 112 111 187 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..5 : Factor w/ 124 levels "","      라면",..: 2 123 71 70 124 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..6 : Factor w/ 378 levels "","      나프타",..: 2 377 166 258 378 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..7 : Factor w/ 263 levels "","      휘발유",..: 2 262 142 3 263 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..8 : Factor w/ 318 levels "","      제트유",..: 2 317 148 90 318 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..9 : Factor w/ 322 levels "","      등유",..: 2 321 146 3 322 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..10: Factor w/ 401 levels "","      경유",..: 2 400 158 176 401 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..11: Factor w/ 398 levels "","      벙커C유",..: 2 397 128 305 398 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..12: Factor w/ 201 levels "","      정제혼합용원료유",..: 2 200 160 172 201 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..13: Factor w/ 109 levels "","      윤활유",..: 2 108 39 3 109 1 1 1 1 1 ...
 $ X7.5.3.수출물가지수.품목별..2015.100..14: Factor w/ 202 levels "","      아스팔트",..: 2 201 133 148 202 1 1 1 1 1 ...

In [6]:
# na 확인
sum(is.na(Export_Items_Original))

[1] 0

In [9]:
# 필요없는 row 정리
head(Export_Items_Original, 5)
Export_Items_Modify_01 <- 
Export_Items_Original[-c(2:5,616:619),]

  통계표  X7.5.3.수출물가지수.품목별..2015.100.
1 항목명1       과일
2 항목명2 달러기준
3 단위    2015=100
4 가중치  0.9
5 변환    원자료
  X7.5.3.수출물가지수.품목별..2015.100..1
1       신선수산물
2 달러기준
3 2015=100
4 0.7
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..2
1       냉동수산물
2 달러기준
3 2015=100
4 2
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..3
1       어육
2 달러기준
3 2015=100
4 0.2
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..4
1       김
2 달러기준
3 2015=100
4 2.5
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..5
1       라면
2 달러기준
3 2015=100
4 2.8
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..6
1       나프타
2 달러기준
3 2015=100
4 4.5
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..7
1       휘발유
2 달러기준
3 2015=100
4 10.3
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..8
1       제트유
2 달러기준
3 2015=100
4 14.9
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..9
1       등유
2 달러기준
3 2015=100
4 0.8
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..10
1       경유
2 달러기준
3 2015=100
4 23.9
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..11
1       벙커C유
2 달러기준
3 2015=100
4 5.7
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..12
1       정제혼합용원료유
2 달러기준
3 2015=100
4 7.7
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..13
1       윤활유
2 달러기준
3 2015=100
4 1.9
5 원자료
  X7.5.3.수출물가지수.품목별..2015.100..14
1       아스팔트
2 달러기준
3 2015=100
4 3.1
5 원자료

In [10]:
# head, tail 확인
head(Export_Items_Modify_01)
tail(Export_Items_Modify_01)

   통계표  X7.5.3.수출물가지수.품목별..2015.100.
1  항목명1       과일
6  1971/01
7  1971/02
8  1971/03
9  1971/04
10 1971/05
   X7.5.3.수출물가지수.품목별..2015.100..1
1        신선수산물
6  8.06
7  7.88
8  8.20
9  8.80
10 8.38
   X7.5.3.수출물가지수.품목별..2015.100..2
1        냉동수산물
6  18.70
7  18.70
8  18.70
9  18.70
10 18.70
   X7.5.3.수출물가지수.품목별..2015.100..3
1        어육
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..4
1        김
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..5
1        라면
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..6
1        나프타
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..7
1        휘발유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..8
1        제트유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..9
1        등유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..10
1        경유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..11
1        벙커C유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..12
1        정제혼합용원료유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..13
1        윤활유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..14
1        아스팔트
6
7
8
9
10

    통계표  X7.5.3.수출물가지수.품목별..2015.100.
610 2021/05 102.80
611 2021/06 102.80
612 2021/07 117.68
613 2021/08 100.80
614 2021/09 99.43
615 2021/10 91.01
    X7.5.3.수출물가지수.품목별..2015.100..1
610 126.95
611 126.83
612 126.18
613 125.99
614 127.73
615 127.67
    X7.5.3.수출물가지수.품목별..2015.100..2
610 113.49
611 118.06
612 128.53
613 131.92
614 131.92
615 132.33
    X7.5.3.수출물가지수.품목별..2015.100..3
610 98.01
611 104.24
612 111.10
613 112.13
614 112.27
615 109.88
    X7.5.3.수출물가지수.품목별..2015.100..4
610 132.74
611 133.15
612 132.53
613 129.53
614 129.60
615 128.45
    X7.5.3.수출물가지수.품목별..2015.100..5
610 101.92
611 101.76
612 101.71
613 101.80
614 101.72
615 101.18
    X7.5.3.수출물가지수.품목별..2015.100..6
610 123.87
611 132.76
612 141.58
613 133.94
614 141.71
615 158.73
    X7.5.3.수출물가지수.품목별..2015.100..7
610 112.32
611 119.01
612 125.41
613 119.09
614 123.88
615 144.52
    X7.5.3.수출물가지수.품목별..2015.100..8
610 113.01
611 119.68
612 121.71
613 116.95
614 127.49
615 137.60
    X7.5.3.수출물가지수.품목별..2015.100..9
610 110.76
611 117.25
612 119.30
613 114.34
614 123.33
615 143.67
    X7.5.3.수출물가지수.품목별..2015.100..10
610 111.96
611 119.33
612 121.03
613 115.20
614 124.62
615 144.92
    X7.5.3.수출물가지수.품목별..2015.100..11
610 131.95
611 143.00
612 145.90
613 143.52
614 160.96
615 171.31
    X7.5.3.수출물가지수.품목별..2015.100..12
610 194.71
611 220.69
612 258.55
613 275.50
614 275.65
615 281.96
    X7.5.3.수출물가지수.품목별..2015.100..13
610 103.95
611 106.77
612 108.99
613 113.50
614 111.80
615 112.09
    X7.5.3.수출물가지수.품목별..2015.100..14
610 141.81
611 145.03
612 145.38
613 149.72
614 149.57
615 157.99

In [11]:
# str 확인: as.character로 변환
for(i in 1:ncol(Export_Items_Modify_01)){
    Export_Items_Modify_01[,i] <- as.character(Export_Items_Modify_01[,i])
}

head(Export_Items_Modify_01)

   통계표  X7.5.3.수출물가지수.품목별..2015.100.
1  항목명1       과일
6  1971/01
7  1971/02
8  1971/03
9  1971/04
10 1971/05
   X7.5.3.수출물가지수.품목별..2015.100..1
1        신선수산물
6  8.06
7  7.88
8  8.20
9  8.80
10 8.38
   X7.5.3.수출물가지수.품목별..2015.100..2
1        냉동수산물
6  18.70
7  18.70
8  18.70
9  18.70
10 18.70
   X7.5.3.수출물가지수.품목별..2015.100..3
1        어육
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..4
1        김
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..5
1        라면
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..6
1        나프타
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..7
1        휘발유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..8
1        제트유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..9
1        등유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..10
1        경유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..11
1        벙커C유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..12
1        정제혼합용원료유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..13
1        윤활유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..14
1        아스팔트
6
7
8
9
10

In [12]:
# str 확인: 공백 제거하기
str(Export_Items_Modify_01)

'data.frame':	611 obs. of  16 variables:
 $ 통계표                                  : chr  "항목명1" "1971/01" "1971/02" "1971/03" ...
 $ X7.5.3.수출물가지수.품목별..2015.100.   : chr  "      과일" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..1 : chr  "      신선수산물" "8.06" "7.88" "8.20" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..2 : chr  "      냉동수산물" "18.70" "18.70" "18.70" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..3 : chr  "      어육" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..4 : chr  "      김" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..5 : chr  "      라면" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..6 : chr  "      나프타" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..7 : chr  "      휘발유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..8 : chr  "      제트유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..9 : chr  "      등유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..10: chr  "      경유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..11: chr  "      벙커C유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..12: chr  "      정제혼합용원료유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..13: chr  "      윤활유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..14: chr  "      아스팔트" "" "" "" ...

In [13]:
# str 확인: 공백 제거하기
for(i in 1:ncol(Export_Items_Modify_01)){
    Export_Items_Modify_01[,i] <- trimws(Export_Items_Modify_01[,i], which = "both")
}

head(Export_Items_Modify_01)

   통계표  X7.5.3.수출물가지수.품목별..2015.100.
1  항목명1 과일
6  1971/01
7  1971/02
8  1971/03
9  1971/04
10 1971/05
   X7.5.3.수출물가지수.품목별..2015.100..1
1  신선수산물
6  8.06
7  7.88
8  8.20
9  8.80
10 8.38
   X7.5.3.수출물가지수.품목별..2015.100..2
1  냉동수산물
6  18.70
7  18.70
8  18.70
9  18.70
10 18.70
   X7.5.3.수출물가지수.품목별..2015.100..3
1  어육
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..4
1  김
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..5
1  라면
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..6
1  나프타
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..7
1  휘발유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..8
1  제트유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..9
1  등유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..10
1  경유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..11
1  벙커C유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..12
1  정제혼합용원료유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..13
1  윤활유
6
7
8
9
10
   X7.5.3.수출물가지수.품목별..2015.100..14
1  아스팔트
6
7
8
9
10

In [15]:
# str 확인: 공백 제거하기
str(Export_Items_Modify_01)

'data.frame':	611 obs. of  16 variables:
 $ 통계표                                  : chr  "항목명1" "1971/01" "1971/02" "1971/03" ...
 $ X7.5.3.수출물가지수.품목별..2015.100.   : chr  "과일" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..1 : chr  "신선수산물" "8.06" "7.88" "8.20" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..2 : chr  "냉동수산물" "18.70" "18.70" "18.70" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..3 : chr  "어육" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..4 : chr  "김" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..5 : chr  "라면" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..6 : chr  "나프타" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..7 : chr  "휘발유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..8 : chr  "제트유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..9 : chr  "등유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..10: chr  "경유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..11: chr  "벙커C유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..12: chr  "정제혼합용원료유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..13: chr  "윤활유" "" "" "" ...
 $ X7.5.3.수출물가지수.품목별..2015.100..14: chr  "아스팔트" "" "" "" ...

In [17]:
# colunm 이름 변경하기
colnames(Export_Items_Modify_01) <-
c("기간", Export_Items_Modify_01[1,2:ncol(Export_Items_Modify_01)])
colnames(Export_Items_Modify_01)

 [1] "기간"             "과일"             "신선수산물"       "냉동수산물"
 [5] "어육"             "김"               "라면"             "나프타"
 [9] "휘발유"           "제트유"           "등유"             "경유"
[13] "벙커C유"          "정제혼합용원료유" "윤활유"           "아스팔트"

In [21]:
# row 정리
Export_Items_Modify_01 <- 
Export_Items_Modify_01[-1,]

In [22]:
# rownames 정리

rownames(Export_Items_Modify_01) <- c()
head(Export_Items_Modify_01,3)
tail(Export_Items_Modify_01,3)

  기간    과일 신선수산물 냉동수산물 어육 김 라면 나프타 휘발유 제트유 등유
1 1971/01      8.06       18.70
2 1971/02      7.88       18.70
3 1971/03      8.20       18.70
  경유 벙커C유 정제혼합용원료유 윤활유 아스팔트
1
2
3

    기간    과일   신선수산물 냉동수산물 어육   김     라면   나프타 휘발유
608 2021/08 100.80 125.99     131.92     112.13 129.53 101.80 133.94 119.09
609 2021/09 99.43  127.73     131.92     112.27 129.60 101.72 141.71 123.88
610 2021/10 91.01  127.67     132.33     109.88 128.45 101.18 158.73 144.52
    제트유 등유   경유   벙커C유 정제혼합용원료유 윤활유 아스팔트
608 116.95 114.34 115.20 143.52  275.50           113.50 149.72
609 127.49 123.33 124.62 160.96  275.65           111.80 149.57
610 137.60 143.67 144.92 171.31  281.96           112.09 157.99

In [23]:
# 기간수 확인
2021-1971 # 1971~2020년 연수확인: 50
50 * 12 # 1971~2020년의 월수확인: 588
600 + 10 # 1971년 1월~2021년 10월까지 월수확인
nrow(Export_Items_Modify_01)

[1] 50

[1] 600

[1] 610

[1] 610

In [24]:
# YYYY/MM을 YYYY.XX로 변경: stringr 패키지 불러오기
library(stringr)

In [25]:
# YYYY/MM을 YYYY.XX로 변경: '/'를 '.'으로 변경하기
Export_Items_Modify_01[,1] <- str_replace_all(Export_Items_Modify_01[,1], '/', '.')

In [26]:
head(Export_Items_Modify_01)

  기간    과일 신선수산물 냉동수산물 어육 김 라면 나프타 휘발유 제트유 등유
1 1971.01      8.06       18.70
2 1971.02      7.88       18.70
3 1971.03      8.20       18.70
4 1971.04      8.80       18.70
5 1971.05      8.38       18.70
6 1971.06      9.02       18.70
  경유 벙커C유 정제혼합용원료유 윤활유 아스팔트
1
2
3
4
5
6

In [27]:
# str 확인: 기간 외 컬럼 as.numeric으로 변환
str(Export_Items_Modify_01)

'data.frame':	610 obs. of  16 variables:
 $ 기간            : chr  "1971.01" "1971.02" "1971.03" "1971.04" ...
 $ 과일            : chr  "" "" "" "" ...
 $ 신선수산물      : chr  "8.06" "7.88" "8.20" "8.80" ...
 $ 냉동수산물      : chr  "18.70" "18.70" "18.70" "18.70" ...
 $ 어육            : chr  "" "" "" "" ...
 $ 김              : chr  "" "" "" "" ...
 $ 라면            : chr  "" "" "" "" ...
 $ 나프타          : chr  "" "" "" "" ...
 $ 휘발유          : chr  "" "" "" "" ...
 $ 제트유          : chr  "" "" "" "" ...
 $ 등유            : chr  "" "" "" "" ...
 $ 경유            : chr  "" "" "" "" ...
 $ 벙커C유         : chr  "" "" "" "" ...
 $ 정제혼합용원료유: chr  "" "" "" "" ...
 $ 윤활유          : chr  "" "" "" "" ...
 $ 아스팔트        : chr  "" "" "" "" ...

In [28]:
# str 확인: 기간 외 컬럼 as.numeric으로 변환
for(i in 2:ncol(Export_Items_Modify_01)){
    Export_Items_Modify_01[,i] <- as.numeric(Export_Items_Modify_01[,i])
}
str(Export_Items_Modify_01)

'data.frame':	610 obs. of  16 variables:
 $ 기간            : chr  "1971.01" "1971.02" "1971.03" "1971.04" ...
 $ 과일            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 신선수산물      : num  8.06 7.88 8.2 8.8 8.38 9.02 7.65 7.59 7.64 7.9 ...
 $ 냉동수산물      : num  18.7 18.7 18.7 18.7 18.7 18.7 18.7 18.7 18.7 18.7 ...
 $ 어육            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 김              : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 라면            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 나프타          : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 휘발유          : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 제트유          : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 등유            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 경유            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 벙커C유         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 정제혼합용원료유: num  NA NA NA NA NA NA NA NA NA NA ...
 $ 윤활유          : num  NA NA NA NA NA NA NA NA NA NA ...
 $ 아스팔트        : num  NA NA NA NA NA NA NA NA NA NA ...

In [29]:
# NA 발생으로 NA 값 0으로 대체: 각 row별 NA 확인
for(i in 1:ncol(Export_Items_Modify_01)){
    cat(colnames(Export_Items_Modify_01[i]),': ',
        sum(is.na(Export_Items_Modify_01[,i])),
        '\n'
       )
}

기간 :  0
과일 :  408
신선수산물 :  0
냉동수산물 :  0
어육 :  168
김 :  408
라면 :  168
나프타 :  168
휘발유 :  348
제트유 :  288
등유 :  288
경유 :  168
벙커C유 :  168
정제혼합용원료유 :  408
윤활유 :  492
아스팔트 :  408

In [30]:
# 과일 NA 확인: 408개
Export_Items_Modify_01[408:409,c(1,2)]
sum(is.na(Export_Items_Modify_01[,2]))

    기간    과일
408 2004.12    NA
409 2005.01 70.61

[1] 408

In [32]:
# 어육 NA 확인: 168개
Export_Items_Modify_01[168:169,c(1,5)]
sum(is.na(Export_Items_Modify_01[,5]))

    기간    어육
168 1984.12     NA
169 1985.01 110.65

[1] 168

In [33]:
# 김 NA 확인: 408개
Export_Items_Modify_01[408:409,c(1,6)]
sum(is.na(Export_Items_Modify_01[,6]))

    기간    김
408 2004.12    NA
409 2005.01 94.79

[1] 408

In [35]:
# 라면 NA 확인: 168개
Export_Items_Modify_01[168:169,c(1,7)]
sum(is.na(Export_Items_Modify_01[,7]))

    기간    라면
168 1984.12    NA
169 1985.01 47.88

[1] 168

In [36]:
# 나프타 NA 확인: 168개
Export_Items_Modify_01[168:169,c(1,8)]
sum(is.na(Export_Items_Modify_01[,8]))

    기간    나프타
168 1984.12    NA
169 1985.01 29.19

[1] 168

In [39]:
# 휘발유 NA 확인: 348개
Export_Items_Modify_01[348:349,c(1,9)]
sum(is.na(Export_Items_Modify_01[,9]))

    기간    휘발유
348 1999.12    NA
349 2000.01 51.23

[1] 348

In [41]:
# 제트유 NA 확인: 288개
Export_Items_Modify_01[288:289,c(1,10)]
sum(is.na(Export_Items_Modify_01[,10]))

    기간    제트유
288 1994.12    NA
289 1995.01 35.33

[1] 288

In [42]:
# 제트유 NA 확인: 288개
Export_Items_Modify_01[288:289,c(1,11)]
sum(is.na(Export_Items_Modify_01[,11]))

    기간    등유
288 1994.12    NA
289 1995.01 35.94

[1] 288

In [44]:
# 경유 NA 확인: 168개
Export_Items_Modify_01[168:169,c(1,12)]
sum(is.na(Export_Items_Modify_01[,12]))

    기간    경유
168 1984.12    NA
169 1985.01 48.84

[1] 168

In [45]:
# 벙커C유 NA 확인: 168개
Export_Items_Modify_01[168:169,c(1,13)]
sum(is.na(Export_Items_Modify_01[,13]))

    기간    벙커C유
168 1984.12    NA
169 1985.01 45.13

[1] 168

In [47]:
# 정제혼합용원료유 NA 확인: 408개
Export_Items_Modify_01[408:409,c(1,14)]
sum(is.na(Export_Items_Modify_01[,14]))

    기간    정제혼합용원료유
408 2004.12    NA
409 2005.01 72.36

[1] 408

In [49]:
# 윤활유 NA 확인: 492개
Export_Items_Modify_01[492:493,c(1,15)]
sum(is.na(Export_Items_Modify_01[,15]))

    기간    윤활유
492 2011.12     NA
493 2012.01 122.52

[1] 492

In [51]:
# 아스팔트 NA 확인: 408개
Export_Items_Modify_01[408:409,c(1,16)]
sum(is.na(Export_Items_Modify_01[,16]))

    기간    아스팔트
408 2004.12    NA
409 2005.01 54.67

[1] 408

# NA값 대체 내용
- 과일: 2005년 1월부터 수출물가지수 기록이 시작되었으므로 2005년 1월 이전 기록은 0으로 대체하기로 함.
- 어육: 1985년 1월부터 수출물가지수 기록이 시작되었으므로 1985년 1월 이전 기록은 0으로 대체하기로 함.
- 김: 2005년 1월부터 수출물가지수 기록이 시작되었으므로 2005년 1월 이전 기록은 0으로 대체하기로 함.
- 라면: 1985년 1월부터 수출물가지수 기록이 시작되었으므로 1985년 1월 이전 기록은 0으로 대체하기로 함.
- 나프타: 1985년 1월부터 수출물가지수 기록이 시작되었으므로 1985년 1월 이전 기록은 0으로 대체하기로 함.
- 휘발유: 2000년 1월부터 수출물가지수 기록이 시작되었으므로 2000년 1월 이전 기록은 0으로 대체하기로 함.
- 제트유: 1995년 1월부터 수출물가지수 기록이 시작되었으므로 1995년 1월 이전 기록은 0으로 대체하기로 함.
- 등유: 1995년 1월부터 수출물가지수 기록이 시작되었으므로 1995년 1월 이전 기록은 0으로 대체하기로 함.
- 경유: 1985년 1월부터 수출물가지수 기록이 시작되었으므로 1985년 1월 이전 기록은 0으로 대체하기로 함.
- 벙커C유: 1985년 1월부터 수출물가지수 기록이 시작되었으므로 1985년 1월 이전 기록은 0으로 대체하기로 함.
- 정제혼합용원료유: 2005년 1월부터 수출물가지수 기록이 시작되었으므로 2005년 1월 이전 기록은 0으로 대체하기로 함.
- 윤활유: 2012년 1월부터 수출물가지수 기록이 시작되었으므로 2012년 1월 이전 기록은 0으로 대체하기로 함.
- 아스팔트: 2005년 1월부터 수출물가지수 기록이 시작되었으므로 2005년 1월 이전 기록은 0으로 대체하기로 함.

In [56]:
# str 확인: 기간 외 컬럼 as.numeric으로 변환
for(i in 2:ncol(Export_Items_Modify_01)){
    Export_Items_Modify_01[,i] <- str_replace_na(Export_Items_Modify_01[,i], 0)
}
str(Export_Items_Modify_01)

'data.frame':	610 obs. of  16 variables:
 $ 기간            : chr  "1971.01" "1971.02" "1971.03" "1971.04" ...
 $ 과일            : chr  "0" "0" "0" "0" ...
 $ 신선수산물      : chr  "8.06" "7.88" "8.2" "8.8" ...
 $ 냉동수산물      : chr  "18.7" "18.7" "18.7" "18.7" ...
 $ 어육            : chr  "0" "0" "0" "0" ...
 $ 김              : chr  "0" "0" "0" "0" ...
 $ 라면            : chr  "0" "0" "0" "0" ...
 $ 나프타          : chr  "0" "0" "0" "0" ...
 $ 휘발유          : chr  "0" "0" "0" "0" ...
 $ 제트유          : chr  "0" "0" "0" "0" ...
 $ 등유            : chr  "0" "0" "0" "0" ...
 $ 경유            : chr  "0" "0" "0" "0" ...
 $ 벙커C유         : chr  "0" "0" "0" "0" ...
 $ 정제혼합용원료유: chr  "0" "0" "0" "0" ...
 $ 윤활유          : chr  "0" "0" "0" "0" ...
 $ 아스팔트        : chr  "0" "0" "0" "0" ...

In [57]:
# str 확인: 기간 외 NA 값 0으로 대체
for(i in 2:ncol(Export_Items_Modify_01)){
    Export_Items_Modify_01[,i] <- as.numeric(Export_Items_Modify_01[,i])
}
str(Export_Items_Modify_01)

'data.frame':	610 obs. of  16 variables:
 $ 기간            : chr  "1971.01" "1971.02" "1971.03" "1971.04" ...
 $ 과일            : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 신선수산물      : num  8.06 7.88 8.2 8.8 8.38 9.02 7.65 7.59 7.64 7.9 ...
 $ 냉동수산물      : num  18.7 18.7 18.7 18.7 18.7 18.7 18.7 18.7 18.7 18.7 ...
 $ 어육            : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 김              : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 라면            : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 나프타          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 휘발유          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 제트유          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 등유            : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 경유            : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 벙커C유         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 정제혼합용원료유: num  0 0 0 0 0 0 0 0 0 0 ...
 $ 윤활유          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ 아스팔트        : num  0 0 0 0 0 0 0 0 0 0 ...

In [58]:
write.csv(Export_Items_Modify_01, "../Data/Export_Items_Index.csv", row.names = F)

In [59]:
read.csv("../Data/Export_Items_Index.csv")

    기간    과일   신선수산물 냉동수산물 어육   김     라면   나프타 휘발유
1   1971.01 0      8.06       18.70      0      0      0      0      0
2   1971.02 0      7.88       18.70      0      0      0      0      0
3   1971.03 0      8.20       18.70      0      0      0      0      0
4   1971.04 0      8.80       18.70      0      0      0      0      0
5   1971.05 0      8.38       18.70      0      0      0      0      0
6   1971.06 0      9.02       18.70      0      0      0      0      0
7   1971.07 0      7.65       18.70      0      0      0      0      0
8   1971.08 0      7.59       18.70      0      0      0      0      0
9   1971.09 0      7.64       18.70      0      0      0      0      0
10  1971.10 0      7.90       18.70      0      0      0      0      0
11  1971.11 0      7.75       18.70      0      0      0      0      0
12  1971.12 0      7.67       18.64      0      0      0      0      0
13  1972.01 0      8.39       18.70      0      0      0      0      0
14  1972.02 0      8.68       18.70      0      0      0      0      0
15  1972.03 0      8.59       18.70      0      0      0      0      0
16  1972.04 0      8.97       18.70      0      0      0      0      0
17  1972.05 0      8.81       18.70      0      0      0      0      0
18  1972.06 0      9.94       18.70      0      0      0      0      0
19  1972.07 0      7.86       18.70      0      0      0      0      0
20  1972.08 0      7.86       18.70      0      0      0      0      0
21  1972.09 0      8.83       19.47      0      0      0      0      0
22  1972.10 0      8.80       20.53      0      0      0      0      0
23  1972.11 0      8.83       21.05      0      0      0      0      0
24  1972.12 0      8.88       21.05      0      0      0      0      0
25  1973.01 0      9.56       20.79      0      0      0      0      0
26  1973.02 0      9.56       21.05      0      0      0      0      0
27  1973.03 0      9.56       22.65      0      0      0      0      0
28  1973.04 0      9.56       23.20      0      0      0      0      0
29  1973.05 0      9.56       23.20      0      0      0      0      0
30  1973.06 0      9.56       23.20      0      0      0      0      0
... ...     ...    ...        ...        ...    ...    ...    ...    ...
581 2019.05 113.10 112.49     112.77     102.43 128.78 101.76 113.82 112.42
582 2019.06 113.10 115.17     110.45     102.32 128.70 102.12  98.28  99.41
583 2019.07 113.10 115.41     110.20     102.21 128.69 102.09 105.29 107.31
584 2019.08 113.10 114.83     108.86      97.42 125.65 102.45  95.96 100.49
585 2019.09 110.48 114.73     109.69      96.22 125.87 102.25 102.57 104.88
586 2019.10 107.18 114.72     106.21      94.81 128.08 102.09 106.50 102.84
587 2019.11 104.81 114.51     106.22      94.13 128.51 101.98 111.52 107.65
588 2019.12 109.48 114.28     107.46      93.62 128.69 101.92 118.14 107.59
589 2020.01 109.48 114.55     109.41      90.94 129.44 101.89 114.21 104.29
590 2020.02 109.48 111.73     109.16      90.05 128.07 101.76  98.59  94.41
591 2020.03 109.48 111.81     109.23      91.73 123.08 102.23  58.40  53.10
592 2020.04 109.48 112.14     102.44      90.17 122.63 102.15  36.12  29.34
593 2020.05 109.48 115.06     100.95      87.10 123.95 102.28  52.23  46.52
594 2020.06 109.48 115.23     102.70      86.32 124.89 102.22  73.80  64.58
595 2020.07 109.48 115.85     105.13      85.62 125.60 102.36  81.43  67.61
596 2020.08 109.48 116.26     106.90      85.88 126.23 102.52  81.67  70.88
597 2020.09 109.48 118.65     104.18      86.13 128.07 102.59  81.39  68.91
598 2020.10 109.48 124.92     105.25      88.63 130.97 102.67  79.58  67.64
599 2020.11 109.48 127.62     107.50      92.29 133.79 102.83  77.77  68.70
600 2020.12 109.48 127.79     107.15      92.72 136.19 102.95  91.09  79.10
601 2021.01 109.48 126.17     106.10      92.82 136.33 102.98 105.26  88.92
602 2021.02 109.50 123.38     106.64      91.64 134.72 102.65 116.23 100.16
603 2021.03 102.80 121.72     108.41      92.50 133.14 102.01 122.15 107.92
604 2021.04 102.80 125.06     110.72      94.88 132.50 101.93 117.40 108.22
605 2021.05 102.80 126.95     113.49      98.01 132.74 101.92 123.87 112.32
606 2021.06 102.80 126.83     118.06     104.24 133.15 101.76 132.76 119.01
607 2021.07 117.68 126.18     128.53     111.10 132.53 101.71 141.58 125.41
608 2021.08 100.80 125.99     131.92     112.13 129.53 101.80 133.94 119.09
609 2021.09  99.43 127.73     131.92     112.27 129.60 101.72 141.71 123.88
610 2021.10  91.01 127.67     132.33     109.88 128.45 101.18 158.73 144.52
    제트유 등유   경유   벙커C유 정제혼합용원료유 윤활유 아스팔트
1   0      0      0      0       0                0      0
2   0      0      0      0       0                0      0
3   0      0      0      0       0                0      0
4   0      0      0      0       0                0      0
5   0      0      0      0       0                0      0
6   0      0      0      0       0                0      0
7   0      0      0      0       0                0      0
8   0      0      0      0       0                0      0
9   0      0      0      0       0                0      0
10  0      0      0      0       0                0      0
11  0      0      0      0       0                0      0
12  0      0      0      0       0                0      0
13  0      0      0      0       0                0      0
14  0      0      0      0       0                0      0
15  0      0      0      0       0                0      0
16  0      0      0      0       0                0      0
17  0      0      0      0       0                0      0
18  0      0      0      0       0                0      0
19  0      0      0      0       0                0      0
20  0      0      0      0       0                0      0
21  0      0      0      0       0                0      0
22  0      0      0      0       0                0      0
23  0      0      0      0       0                0      0
24  0      0      0      0       0                0      0
25  0      0      0      0       0                0      0
26  0      0      0      0       0                0      0
27  0      0      0      0       0                0      0
28  0      0      0      0       0                0      0
29  0      0      0      0       0                0      0
30  0      0      0      0       0                0      0
... ...    ...    ...    ...     ...              ...    ...
581 127.84 125.92 126.45 142.70  121.56            89.29 129.79
582 117.40 115.24 114.63 132.02  124.89            89.54 118.79
583 123.50 121.12 120.31 147.37  132.85            89.86 127.83
584 116.84 115.21 114.82 121.32  133.01            87.60 117.22
585 121.70 120.06 119.00 137.08  132.93            87.06 117.98
586 119.39 116.36 117.13 105.04  131.21            87.11 130.12
587 117.85 115.65 116.02  87.04  131.13            87.26 114.02
588 122.14 120.07 120.74  95.23  130.35            87.56 110.49
589 116.39 116.37 117.00 114.08  127.42            88.27 111.69
590  98.90  97.36 100.17 102.51  126.26            87.20 104.87
591  61.75  60.72  68.95  69.22  119.19            85.41  73.02
592  36.19  32.83  46.10  51.27   93.54            83.09  64.37
593  44.87  44.62  53.68  58.21   91.74            83.46  65.95
594  64.15  63.61  71.10  80.70   93.37            84.15  93.50
595  69.56  67.85  76.73  87.21   95.39            82.30 113.45
596  69.95  66.87  74.74  93.11  113.12            80.53 117.70
597  63.42  60.73  67.12  87.35  115.52            80.39 109.97
598  66.57  64.29  66.97  90.31  115.52            80.27 107.96
599  72.49  70.52  72.61  96.76  135.12            80.96 109.86
600  84.81  82.88  84.25 104.86  139.29            83.07 116.78
601  91.35  89.60  91.12 114.18  145.98            82.85 123.07
602 102.93 100.59 103.27 127.30  156.60            84.35 132.95
603 106.17 103.13 106.18 134.35  162.04            89.59 145.53
604 106.39 103.05 104.73 130.45  180.94            96.29 146.68
605 113.01 110.76 111.96 131.95  194.71           103.95 141.81
606 119.68 117.25 119.33 143.00  220.69           106.77 145.03
607 121.71 119.30 121.03 145.90  258.55           108.99 145.38
608 116.95 114.34 115.20 143.52  275.50           113.50 149.72
609 127.49 123.33 124.62 160.96  275.65           111.80 149.57
610 137.60 143.67 144.92 171.31  281.96           112.09 157.99