In [1]:
library(stringr)

In [2]:
interestRate.main <-read.csv('../Data/금리2.csv', fileEncoding = "euc-kr", header = F)
head(interestRate.main)

  V1      V2
1 통계표  4.1.2 시장금리(월,분기,년)
2 항목명1 국고채(1년)
3 단위    연%
4 변환    원자료
5 2000/01
6 2000/02 8.530

In [3]:
tail(interestRate.main,7)

    V1
267 2021/11
268    4.1.2 시장금리(월
269 년)
270 통계담당 : 한국은행 금융시장국 자금시장팀(02-759-4508)
271 주 : 1) 월평균(영업일기준)
272 2) 국고채(30년) : 2012.9월부터 발행
273 3) 통안증권(1년) : 2011.5.1부터 364일물(할인채)에서 1년물(이표채)로 고시기준 변경
    V2
267 1.339
268 분기
269
270  채권시장팀(02-759-5630)
271
272
273

In [4]:
colnames(interestRate.main)<-c('월간','국고채(1년)')
head(interestRate.main)

  월간    국고채(1년)
1 통계표  4.1.2 시장금리(월,분기,년)
2 항목명1 국고채(1년)
3 단위    연%
4 변환    원자료
5 2000/01
6 2000/02 8.530

In [5]:
interestRate.main<-interestRate.main[c(-(1:5),-(268:273)),]
head(interestRate.main)
tail(interestRate.main)

   월간    국고채(1년)
6  2000/02 8.530
7  2000/03 8.350
8  2000/04 8.340
9  2000/05 8.340
10 2000/06 8.240
11 2000/07 7.560

    월간    국고채(1년)
262 2021/06 0.798
263 2021/07 0.910
264 2021/08 1.001
265 2021/09 1.073
266 2021/10 1.178
267 2021/11 1.339

In [6]:
rownames(interestRate.main)<- c()
tail(interestRate.main)

    월간    국고채(1년)
257 2021/06 0.798
258 2021/07 0.910
259 2021/08 1.001
260 2021/09 1.073
261 2021/10 1.178
262 2021/11 1.339

In [7]:
str(interestRate.main)

'data.frame':	262 obs. of  2 variables:
 $ 월간       : Factor w/ 273 levels "   4.1.2 시장금리(월",..: 4 5 6 7 8 9 10 11 12 13 ...
 $ 국고채(1년): Factor w/ 230 levels ""," 채권시장팀(02-759-5630)",..: 226 225 224 224 223 222 220 221 219 218 ...

In [8]:
for (i in 2: ncol(interestRate.main)){ 
    interestRate.main[,i] <- as.numeric(str_replace_all(as.character(interestRate.main[,i]),',',''))

}

In [9]:
str(interestRate.main)

'data.frame':	262 obs. of  2 variables:
 $ 월간       : Factor w/ 273 levels "   4.1.2 시장금리(월",..: 4 5 6 7 8 9 10 11 12 13 ...
 $ 국고채(1년): num  8.53 8.35 8.34 8.34 8.24 7.56 7.2 7.26 7.13 6.96 ...

In [10]:
colSums(is.na(interestRate.main))

       월간 국고채(1년)
          0           0

In [11]:
interestRate.main

    월간    국고채(1년)
1   2000/02 8.53
2   2000/03 8.35
3   2000/04 8.34
4   2000/05 8.34
5   2000/06 8.24
6   2000/07 7.56
7   2000/08 7.20
8   2000/09 7.26
9   2000/10 7.13
10  2000/11 6.96
11  2000/12 6.67
12  2001/01 6.04
13  2001/02 5.51
14  2001/03 5.81
15  2001/04 6.20
16  2001/05 6.10
17  2001/06 5.80
18  2001/07 5.47
19  2001/08 5.05
20  2001/09 4.75
21  2001/10 4.42
22  2001/11 4.88
23  2001/12 5.34
24  2002/01 5.23
25  2002/02 4.96
26  2002/03 5.26
27  2002/04 5.42
28  2002/05 5.42
29  2002/06 5.38
30  2002/07 5.34
... ...     ...
233 2019/06 1.560
234 2019/07 1.478
235 2019/08 1.186
236 2019/09 1.228
237 2019/10 1.298
238 2019/11 1.386
239 2019/12 1.350
240 2020/01 1.316
241 2020/02 1.214
242 2020/03 1.030
243 2020/04 0.893
244 2020/05 0.779
245 2020/06 0.719
246 2020/07 0.689
247 2020/08 0.671
248 2020/09 0.705
249 2020/10 0.680
250 2020/11 0.700
251 2020/12 0.719
252 2021/01 0.695
253 2021/02 0.671
254 2021/03 0.684
255 2021/04 0.659
256 2021/05 0.611
257 2021/06 0.798
258 2021/07 0.910
259 2021/08 1.001
260 2021/09 1.073
261 2021/10 1.178
262 2021/11 1.339

In [12]:
interestRate.main$월간 <- str_replace_all(as.character(interestRate.main[,1]),'/','.')

In [13]:
head(interestRate.main)

  월간    국고채(1년)
1 2000.02 8.53
2 2000.03 8.35
3 2000.04 8.34
4 2000.05 8.34
5 2000.06 8.24
6 2000.07 7.56

In [14]:
write.csv(interestRate.main,"../Data/INTERESTATEdata.csv",row.names=F)